### ISSUE TITLE
The VSCode's Testing tab does not show anything

### ISSUE THREAD

**Issue by aqjune** [Release-Candidate/vscode-ocaml-expect-inline#1]
**Describe the bug**
The VSCode's Testing tab does not show anything

![image](https://user-images.githubusercontent.com/6484889/225365267-b9c3a93d-cf3f-4285-8524-428c405aad99.png)

My dune project's directory has this directory hierarchy (.ml files are omitted):
```
ProjectName
- dune-project
- ProjectName.opam
- bin
  - dune
- lib
  - dune
- test <- this is just a dummy directory, containing nothing
  - dune
```

I think dune is correctly configured because my VSCode can successfully typecheck variables and highlight compilation errors from .ml files.

**To Reproduce**
1. Install the plugin and wait
2. Click the 'Testing' tab on the left

**Expected behavior**
A list of tests are shown

**Screenshots**

**Logs**
> If applicable, add logs of the extension (Output of `Expect and Inline Tests`), the Extension Host (Ouput of `Extension Host`) and Window (Output of `Window`).

I would like to report, but where can I find these?

**Example OCaml project**

**Environment (please complete the following information):**
 - Version of the extension: v0.2.0
 - Version of VS Code: 1.76.1
 - OS: [e.g.Linux] WSL2, Ubuntu

**Additional context**

**Comment by aqjune** [comment]
>     If applicable, add logs of the extension (Output of Expect and Inline Tests), the Extension Host (Ouput of Extension Host) and Window (Output of Window).
> 
> I would like to report, but where can I find these?

Okay, I think I could get the message of `Output of Expect and Inline Tests` from the Output tab at the bottom of VSCode:

```
Processing workspace armv8opt
Error calling dune in (replaced with ProjectName. :) ), can't use dune! Error message: """spawn dune ENOENT"""
Finished adding new tests.
```

I guess the reason is that vscode-ocaml-expect-inline does not detect my `opam` that was locally configured for this project. `dune` is only available in this local `opam`, but not globally installed, so this error seems to happen.

**Comment by Release-Candidate** [comment]
Oh, yes. Unfortunately I have yet to find a way to use the same environment the OCaml Plattform extension uses. Or do something like calling `eval $(opam env)` in the project root to set the correct Opam environment.

A workaround to get it to work is to start VS Code in the correct Opam environment.
Like this:
```
cd YOUR_PROJECT
eval $(opam env)
code ./
```
After the call to `eval $(opam env)` all  executables should be in the current PATH, including `dune`.

**Comment by aqjune** [comment]
```
cd YOUR_PROJECT
eval $(opam env)
code ./
```

This seems to work for me at the moment, thanks! I will use this trick until it is fully solved. :)

**Comment by Release-Candidate** [comment]
Glad to hear!
I report back as soon as I have found a solution and updated both extensions.

**Comment by Release-Candidate** [comment]
The new version 0.3.0 should fix this. 
At least an error message window should show up now if Dune doesn't work.
