### ISSUE TITLE
feature request: show diffs in errors messages

### ISSUE THREAD

**Issue by Alizter** [Release-Candidate/vscode-ocaml-expect-inline#6]
When we have diffs in error messages they are simply rendered as plain text:
![image](https://user-images.githubusercontent.com/8614547/227362541-aa8c6869-f54f-4675-9766-b0ce29b897a9.png)

It would be nice if they were rendered diffs.

**Comment by Release-Candidate** [comment]
They were diffs in the previous version, I just didn't like them much with the test failure outputs in the Dune project. The problem with the way VS Code handles them is that either the diff is displayed or the whole failure message (which I always append to the tests).
Adding them back in and making them configureable isn't much work, so I'll do that.

**Comment by Release-Candidate** [comment]
Just released a new version. I did not make this configurable, as the whole output can still be seen by hovering the `let%expect_test` stanza above the diff.

**Comment by Release-Candidate** [comment]
Works since version 0.6.0

**Comment by Alizter** [comment]
Looks great thanks!

![image](https://user-images.githubusercontent.com/8614547/228216137-1750b2da-4c19-40d7-9f22-bb5df99adc2c.png)
