### ISSUE TITLE
Cannot cancel tests when waiting for Dune lock

### ISSUE THREAD

**Issue by Alizter** [Release-Candidate/vscode-ocaml-expect-inline#9]
When the extensions are waiting for Dune to run the tests, it appears that they are waiting for the lock to be released. However when pressing cancel the tests are not cancelled.

**Comment by Release-Candidate** [comment]
The new version 0.7.0 fixes this and adds an error message after some time if the lock cannot be acquired

**Comment by Alizter** [comment]
The fix and the message work. Thanks!
